### ISSUE TITLE
No Licence available for RobotoMono repository

### ISSUE THREAD

**Issue by PhilArmstrong** [googlefonts/RobotoMono#26]
Any chance this repo can be explicitly licenced like the main Roboto repo? It would be nice to get this font into Debian, but there’s no way it can be packaged without an explicit licence.

cheers, Phil

**Comment by sprat** [comment]
Up ?

**Comment by ThomasLamprecht** [comment]
Pinging this as it may be a quick/small fix. There's some interest to package this font for Debian, but it seems that the current blocker is that the repo here is missing a license file that clarifies that this source and font artifacts are indeed covered by the Apache 2.0 license.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=819273#80

And sorry if this is stepping out of line, but also mentioning @pichotta which merged in the last commits here and the pair of @davelab6 and @m4rc1e which committed, or respectively, authored the last commit in the sister Roboto repository from the @googlefonts org.

Can we please clarify here that this is indeed under Apache 2.0, like the original Roboto is and the Google fonts site states for the artifacts downloadable there: https://fonts.google.com/specimen/Roboto+Mono#license
It has no pointer to the source, so we cannot deduce that this source here is in fact the one it's build from, and thus covered by Apache 2.0.

**Comment by kesara** [comment]
I'm creating a fonts repository for the [xml2rfc](https://github.com/ietf-tools/xml2rfc/) (the tool used to generate RFCs and Internet-Drafts by IETF). It would be nice if maintainers could include the license in this repository.

**Comment by eliheuer** [comment]
I made a PR adding the license, sorry this issue was ignored for so long, it is Apache License 2.0 on the Google Fonts site: https://fonts.google.com/specimen/Roboto+Mono/about?query=roboto+mono

**Comment by PhilArmstrong** [comment]
Great! Once the PR is merged I’ll ping the packagers, unless they’re already watching this GH issue.

**Comment by davelab6** [comment]
> Package maintainer for Fedora here. I'm not comfortable pulling the files from one repository, but the license from another. As a result, I can't update the TTF version of the font since it's no longer included in the google/fonts archive.

Why isn't it in that archive?

**Comment by PhilArmstrong** [comment]
Thanks to the maintainers for finally fixing this issue :)

**Comment by PhilArmstrong** [comment]
Closing issue, as the repo is now Apache-2.0 licenced.

**Comment by PhilArmstrong** [comment]
@subpop @kesara @ThomasLamprecht Just mentioning you all so you pick up on this. Thanks for all your efforts.
